### ISSUE TITLE
 glFusion CMS 1.7.9 Host Header ATTACK 

### ISSUE THREAD

**Issue by Topsec-bunney** [glFusion/glfusion#483]
After modifying the host value, you can still request to the website. This can easily lead to Man-in-the-MiddleAttack
![javaw_BnoEMfpdDu](https://user-images.githubusercontent.com/73220685/145193374-2de7e8a1-54e1-414c-b0ba-e0b86d818480.png)

**Comment by mark0263** [comment]
Is there a proof of concept that shows how this can be exploited?  I don't disagree with validating the Host (and X-Forwarded-Host) with some type of whitelist.  Looking thru the glFusion code, glFusion does not rely on or user the Host header.  Is this more of a web server concern?

**Comment by Topsec-bunney** [comment]
This problem can be solved through the web server, but because the website uses many absolute paths, this is also one of the unsafe factors. If you fix it, you can change the absolute path of the website to a relative path, which is safer.

**Comment by walterrowe** [comment]
I have always disliked having absolute paths. It makes it more difficult to move sites from one host to another, or clone a production site to a test environment. Relative paths would be a welcome improvement.

Walter

**Comment by leegarner** [comment]
It wouldn't hurt to validate the host header, I'm not sure if it would hurt
anything since everything gets redirected to site_url or site_admin_url
anyway. Normally spoofing a host header will simply allow you to load a
virtual host by curling the IP address

The "absolute" path is determined by the web server config. Normally you'd
have a directive setting the document root to, in your case,
<some_path>/glfusion-1.7.9/public_html.  If the complete glFusion package
is installed in the web server's document root, then the path would look
like you describe, which also allows access to the "private" directory
which is a bigger concern (though not a critical issue unless the web
server is misconfigured).

**Comment by mark0263** [comment]
Closing as this is a web server configuration concern
