### ISSUE TITLE
Consolidate all site data under a single directory

### ISSUE THREAD

**Issue by walterrowe** [glFusion/glfusion#6]
Each plugin currently has it's own data / media directory. Move these all under a single top-level site data directory. You can create subdirs inside by plugin name (/data/media, /data/forums, /data/filemgmt, etc). This allows us to protect this area with .htaccess, and allows easier site cloning and code updates. It also makes it easier to document where site data is stored.

**Comment by walterrowe** [comment]
I’m adding a update to this request. If I want to containerize an instance of glfusion, having a single data directory would make it easier to map that into the container for persistence across container updates.

**Comment by leegarner** [comment]
To throw in another comment, one blocker to Docker is logging. A config item to send logs to syslog would solve that.

**Comment by walterrowe** [comment]
If your logs are in your data directory then it goes in the mapped persistence, but yes syslog would also solve that.

**Comment by mark0263** [comment]
I'm finally going to tackle this one for glFusion v2.  

This is really the primary item holding back containerization as Walter has pointed out.  The plan is (for now):

- public_html/data/ directory - this will be hard coded - the reason is I need a place to find siteconfig.php that is consistent.
- under the data directory - each plugin can create their own directory and to store whatever they need to store
- will implement a getPublicDataDir() call to allow returning the full path and URL if needed

Not sure what I'm going to do about upgrades at this point - my plan is to do this so it doesn't break an existing site upgrading to the latest release - with instructions on how to migrate data to the new structure.

**Comment by leegarner** [comment]
Funny, I was looking at this issue the other day and thinking about it. For
current plugins that store in public_html/plugin or private/plugin/... I'd
probably have a config var like Filemgmt uses so the admin can change at
their leisure. New installations will default to the new path which means
the value needs to be set during upgrade.

What I did for photo competitions is to store all the submitted images
under data and resize/copy them on demand into a cache directory under
public_html. It seems like always delivering images through PHP would be
inefficient, but it accomplishes the goal of only storing original images
and only under private/data..  Another thought, especially for regular
article images, is to just mount public_html/images externally. It looks
like there might be a few images in there that may better be in the theme
dir.

For load-balanced environments there are a few other things to think about,
such as the plugin upload.  This is probably an edge case and most likely
the admin would need to mount at least private/plugins and all of
public_html externally. For now just separating all user-generated content
will go a long way towards getting there.

**Comment by walterrowe** [comment]
Just getting everything under a common data directory is a huge step forward. It makes so many things better. It is a single location where all site-specific data is stored - user profile images, media gallery, article images, file manager, etc.

**Comment by mark0263** [comment]
I've done the first commit to get the process started - moving db-config to private/data/ and siteconfig.php to public_html/data/.

**You can either manually move the files or run the standard Upgrade process and it will migrate them.**

dvlpupdate.php **does not** migrate the files - use the standard glFusion Upgrade.

**Comment by mark0263** [comment]
all core functions should now allow operating with a private/data and public_html/data directory.

The overall lift was actually pretty small since most items have configuration settings to control where data is stored so things like Forum, Media Gallery and FileMgmt didn't really require any major code changes. 

I did do a little re-organizing as well - created an assets/ directory and moved static images that ship with glFusion into that directory - out of the image/ directory (and yes, Lee is right, some of these should really go back to the layout directory).  Also did away with the mediaobject/ directory under the Media Gallery - also moving some of the static items to Media Gallery's assets/ directory.

I'm sure there is more work to do - but it is a pretty good start.

**Comment by mark0263** [comment]
I think it is all working well - not sure if anyone else is tracking and testing moving data under /data/. 

Also - the docker build is now working as well.

**Comment by TJ-Support** [comment]
Hello. I think this is a great idea.

I haven't had a chance to do any testing yet, but I have been asked to add a comment here about the images folder.

When deleting obsolute files on upgrading, will this remove all of the files in the images directory? I am asking because all of my images, site wide, are in that folder that are not necessarily connected solely with glfusion.

**Comment by mark0263** [comment]
TJ - I'm excluding the /images/ directory from any automatic deleting.  It will be a manual process if the site owner wants to remove.  Too risky to try and automatically delete.  The same is true for the Media Gallery mediaojbects/ directory - it will not be removed thru any upgrade checks.

**Comment by mark0263** [comment]
Implemented in glFusion v2 - any additional directories to consolidate should be opened as new issues.
